export const genderOptions = [
  { label: "Male", value: "MALE" },
  { label: "Female", value: "FEMALE" },
];

export const professionOptions = [
  { label: "Salaried", value: "SALARIED" },
  { label: "Business Owner", value: "BUSINESS_OWNER" },
  { label: "Self Employed", value: "SELF_EMPLOYED" },
];

export const districts = [
  { label: "Bagerhat", value: "BAGERHAT" },
  { label: "Bandarban", value: "BANDARBAN" },
  { label: "Barguna", value: "BARGUNA" },
  { label: "Barisal", value: "BARISAL" },
  { label: "Bhola", value: "BHOLA" },
  { label: "Bogura", value: "BOGURA" },
  { label: "Brahmanbaria", value: "BRAHMANBARIA" },
  { label: "Chandpur", value: "CHANDPUR" },
  { label: "Chattogram", value: "CHATTOGRAM" },
  { label: "Chuadanga", value: "CHUADANGA" },
  { label: "Cox's Bazar", value: "COX'S BAZAR" },
  { label: "Cumilla", value: "CUMILLA" },
  { label: "Dhaka", value: "DHAKA" },
  { label: "Dinajpur", value: "DINAJPUR" },
  { label: "Faridpur", value: "FARIDPUR" },
  { label: "Feni", value: "FENI" },
  { label: "Gaibandha", value: "GAIBANDHA" },
  { label: "Gazipur", value: "GAZIPUR" },
  { label: "Gopalganj", value: "GOPALGANJ" },
  { label: "Habiganj", value: "HABIGANJ" },
  { label: "Jamalpur", value: "JAMALPUR" },
  { label: "Jashore", value: "JASHORE" },
  { label: "Jhalokathi", value: "JHALOKATHI" },
  { label: "Jhenaidah", value: "JHENAIDAH" },
  { label: "Joypurhat", value: "JOYPURHAT" },
  { label: "Khagrachari", value: "KHAGRACHARI" },
  { label: "Khulna", value: "KHULNA" },
  { label: "Kishoreganj", value: "KISHOREGANJ" },
  { label: "Kurigram", value: "KURIGRAM" },
  { label: "Kushtia", value: "KUSHTIA" },
  { label: "Lakshmipur", value: "LAKSHMIPUR" },
  { label: "Lalmonirhat", value: "LALMONIRHAT" },
  { label: "Madaripur", value: "MADARIPUR" },
  { label: "Magura", value: "MAGURA" },
  { label: "Manikganj", value: "MANIKGANJ" },
  { label: "Meherpur", value: "MEHERPUR" },
  { label: "Moulvibazar", value: "MOULVIBAZAR" },
  { label: "Munshiganj", value: "MUNSHIGANJ" },
  { label: "Mymensingh", value: "MYMENSINGH" },
  { label: "Naogaon", value: "NAOGAON" },
  { label: "Narail", value: "NARAIL" },
  { label: "Narayanganj", value: "NARAYANGANJ" },
  { label: "Narsingdi", value: "NARSINGDI" },
  { label: "Natore", value: "NATORE" },
  { label: "Netrokona", value: "NETROKONA" },
  { label: "Nilphamari", value: "NILPHAMARI" },
  { label: "Noakhali", value: "NOAKHALI" },
  { label: "Pabna", value: "PABNA" },
  { label: "Panchagarh", value: "PANCHAGARH" },
  { label: "Patuakhali", value: "PATUAKHALI" },
  { label: "Pirojpur", value: "PIROJPUR" },
  { label: "Rajbari", value: "RAJBARI" },
  { label: "Rajshahi", value: "RAJSHAHI" },
  { label: "Rangamati", value: "RANGAMATI" },
  { label: "Rangpur", value: "RANGPUR" },
  { label: "Satkhira", value: "SATKHIRA" },
  { label: "Shariatpur", value: "SHARIATPUR" },
  { label: "Sherpur", value: "SHERPUR" },
  { label: "Sirajganj", value: "SIRAJGANJ" },
  { label: "Sunamganj", value: "SUNAMGANJ" },
  { label: "Sylhet", value: "SYLHET" },
  { label: "Tangail", value: "TANGAIL" },
  { label: "Thakurgaon", value: "THAKURGAON" },
];

export const tenureOptions = [
  { label: "12 Months", value: 12 },
  { label: "24 Months", value: 24 },
  { label: "36 Months", value: 36 },
  { label: "48 Months", value: 48 },
  { label: "60 Months", value: 60 },
  { label: "72 Months", value: 72 },
];

export const businessOwnerOptions = [
  { label: "Sole Proprietorship", value: "PROPRIETOR" },
  { label: "Partnership", value: "PARTNER" },
  { label: "Corporation", value: "CORPORATION" },
  { label: "LLC", value: "LLC" },
  { label: "Cooperative", value: "COOPERATIVE" },
  { label: "Joint Venture", value: "JOINT_VENTURE" },
  { label: "Franchise", value: "FRANCHISE" },
  // { label: "Non-Profit Organization", value: "NON_PROFIT_ORGANIZATION" },
  // { label: "Private Limited Company", value: "PRIVATE_LIMITED_COMPANY" },
  // { label: "Public Limited Company", value: "PUBLIC_LIMITED_COMPANY" },
];

export const businessTypeOptions = [
  { label: "Retail", value: "RETAIL" },
  { label: "Wholesale", value: "WHOLESALE" },
  { label: "Manufacturing", value: "MANUFACTURING" },
];

export const tradeLicenseExperieOptions = [
  { label: "1 Year", value: 1 },
  { label: "2 Years", value: 2 },
  { label: "3 Years", value: 3 },
  { label: "4 Years", value: 4 },
  { label: "5 Years", value: 5 },
  { label: "6 Years", value: 6 },
  { label: "7 Years", value: 7 },
  { label: "8 Years", value: 8 },
  { label: "9 Years", value: 9 },
  { label: "10 Years", value: 10 },
];
